### ISSUE TITLE
Unable to create cv2.imframe in 'pvf' mode

### ISSUE THREAD

**Issue by Republican31** [PeterStine/OIT-Robosub#19]
I'm trying to run our our main.py file in 'pvf' mode (As opposed to 'rvi' mode, which seems to work). When doing this, I receive the following error.

```
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    vid_process.vid_test("pvf")
  File "C:\Users\CPURe\Documents\RoboSub\SubCode\OIT-Robosub\python_code\vid_process.py", line 47, in vid_test
    cv2.imshow('frame', frame)
cv2.error: OpenCV(3.4.3) C:\projects\opencv-python\opencv\modules\highgui\src\window.cpp:356: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'
```

I tried creating a frame with a color instead, but it didn't work out so well.

**Comment by PeterStine** [comment]
This may help:
https://stackoverflow.com/a/41672017/4106982
